CREATE OR REPLACE TRIGGER TR_EMPLEADO_AU1
BEFORE UPDATE ON P_EMPLEADO
FOR EACH ROW
WHEN (OLD.VIGENCIA = 'V' AND NEW.VIGENCIA = 'R')
DECLARE 
    NOMBRE_CARGO P_CARGO.NOMBRE%TYPE;
BEGIN

    --GUARDAMOS INFORMACION DE RETIRADO
    SELECT NOMBRE INTO NOMBRE_CARGO FROM P_CARGO C
    WHERE C.ID_CARGO = :OLD.ID_CARGO;
    
    INSERT INTO RETIRADOS VALUES(:OLD.ID_EMPLEADO,:OLD.NOMBRE,:OLD.APELLIDO_PATERNO,
               :OLD.APELLIDO_MATERNO,:OLD.TELEFONO,:OLD.CORREO_ELECTRONICO,
                NOMBRE_CARGO,:OLD.NUM_DOC_IDENTIDAD);
    
    --ELIMINAR SU HORARIO,ACTIVIDADES,Y SU ENCARGO
    DELETE FROM P_EMPLEADOXHORARIO
    WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO;
    
    DELETE FROM P_ENCARGADO_ACTIVIDADES
    WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO;
    
    DELETE FROM P_EMPLEADOXACTIVIDAD
    WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO;
    
    DELETE FROM P_MARCACION
    WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO;   
END;

SELECT *FROM RETIRADOS;
DROP TABLE RETIRADOS;

UPDATE P_EMPLEADO SET VIGENCIA = 'R'
WHERE  ID_EMPLEADO = '9136852470';
/
CREATE OR REPLACE TRIGGER TR_NOMINA
BEFORE UPDATE ON P_MARCACION
FOR EACH ROW
WHEN (OLD.VIGENCIA = 'V' AND NEW.VIGENCIA = 'R')
DECLARE 
    NOMBRE_CARGO P_CARGO.NOMBRE%TYPE;
BEGIN

    --GUARDAMOS INFORMACION DE RETIRADO
    SELECT NOMBRE INTO NOMBRE_CARGO FROM P_CARGO C
    WHERE C.ID_CARGO = :OLD.ID_CARGO;
    
    INSERT INTO RETIRADOS VALUES(:OLD.ID_EMPLEADO,:OLD.NOMBRE,:OLD.APELLIDO_PATERNO,
            :OLD.APELLIDO_MATERNO,:OLD.TELEFONO,:OLD.CORREO_ELECTRONICO,
                NOMBRE_CARGO,:OLD.NUM_DOC_IDENTIDAD);
    
    --ELIMINAR SU HORARIO,ACTIVIDADES,Y SU ENCARGO
    DELETE FROM P_EMPLEADOXHORARIO
    WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO;
    
    DELETE FROM P_ENCARGADO_ACTIVIDADES
    WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO;
    
    DELETE FROM P_EMPLEADOXACTIVIDAD
    WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO;
    
    DELETE FROM P_MARCACION
    WHERE ID_EMPLEADO = :OLD.ID_EMPLEADO;   
END;